version: "2"
services:
  db:
    image: mysql:latest
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_DATABASE=ProjectDB
    ports:
      - 3306:3306
  web:
    image: project/project-web
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=project
      - DATABASE_PORT=3306