version: "2"
services:
  db:
    image: mysql:latest
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_DATABASE=ProjectDB
    ports:
      - 3306:3306